# --------------------------------------------------
# Commands to run this compose file:
#     - docker-compose -p comp3095-wellness -f docker-compose.yml up -d
#     This command will start the containers in detached mode (-d) without rebuilding the images (if they already exist)
#
#     - docker-compose -p comp3095-wellness -f docker-compose.yml up -d --build
#     This command force the rebuild of images, even if the images already exist
# ------------------------------------------------
# version: '3.8'

services:
  wellness-DB-postgres:
    image: postgres:15
    container_name: wellness-DB-postgres
    environment:
      POSTGRES_USER: jamesjones
      POSTGRES_PASSWORD: 100898394
      POSTGRES_DB: wellness-resource-serviceDB
    ports:
      - "5481:5432"
    volumes:
      - ./docker/integrated/postgres/wellness-service/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U jamesjones" ]
      interval: 5s
      timeout: 5s
      retries: 5

  wellness-DB-redis:
    image: redis:latest
    container_name: wellness-DB-redis
    ports:
      - "6381:6379"

  wellness-service:
    build: ./wellness-resource-service
    image: wellness-service:1.0
    container_name: wellness-service
    ports:
      - "8081:8081"
    depends_on:
      - wellness-DB-redis
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5481/wellness-resource-serviceDB
      SPRING_DATASOURCE_USERNAME: jamesjones
      SPRING_DATASOURCE_PASSWORD: 100898394
      SPRING_DATA_REDIS_HOST: wellness-DB-redis
      SPRING_DATA_REDIS_PORT: 6379

  event-DB-postgres:
    image: postgres:15
    container_name: event-DB-postgres
    environment:
      POSTGRES_USER: omar
      POSTGRES_PASSWORD: eventservice
      POSTGRES_DB: event-serviceDB
    ports:
      - "5433:5432"

  event-service:
    build: ./event-service
    image: event-service:1.0
    container_name: event-service
    ports:
      - "8033:8033"
    depends_on:
      - event-DB-postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5433/event-serviceDB
      SPRING_DATASOURCE_USERNAME: omar
      SPRING_DATASOURCE_PASSWORD: eventservice

  goal-DB-mongo:
    image: mongo:latest
    container_name: goal-DB-mongo
    ports:
      - "27087:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: goal-tracking-service

  goal-service:
    build: ./goal-tracking-service
    image: mongo:latest
    container_name: goal-service
    ports:
      - "8087:8087"
    depends_on:
      - goal-DB-mongo
    environment:
      SPRING_DATA_MONGODB_HOST: goal-DB-mongo
      SPRING_DATA_MONGODB_USERNAME: admin
      SPRING_DATA_MONGODB_PASSWORD: password
      SPRING_DATA_MONGODB_DATABASE: goal-tracking-service

#  pgadmin:
#    image: dpage/pgadmin4:9.2
#    ports:
#      - "8888:80"
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=user@domain.ca
#      - PGADMIN_DEFAULT_PASSWORD=password
#    container_name: pgadmin_wellness-resource-service

# -------------------- Named volumes --------------------
volumes:
  wellness-resource-service_data: