# --------------------------------------------------
# Commands to run this compose file:
#     - docker-compose -p comp3095-wellness -f docker-compose.yml up -d
#     This command will start the containers in detached mode (-d) without rebuilding the images (if they already exist)
#
#     - docker-compose -p comp3095-wellness -f docker-compose.yml up -d --build
#     This command force the rebuild of images, even if the images already exist
# ------------------------------------------------
# version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: jamesjones
      POSTGRES_PASSWORD: 100898394
      POSTGRES_DB: wellness-resource-serviceDB
    ports:
      - "5432:5432"
    volumes:
      - ./docker/integrated/postgres/wellness-service/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U jamesjones" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: wellness-redis
    ports:
      - "6379:6379"

  wellness-service:
    build: ./wellness-resource-service
    image: wellness-service:1.0
    container_name: wellness-service
    ports:
      - "8081:8081"
    depends_on:
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/wellness-resource-serviceDB
      SPRING_DATASOURCE_USERNAME: jamesjones
      SPRING_DATASOURCE_PASSWORD: 100898394

  pgadmin:
    image: dpage/pgadmin4:9.2
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.ca
      - PGADMIN_DEFAULT_PASSWORD=password
    container_name: pgadmin_wellness-resource-service

# -------------------- Named volumes --------------------
volumes:
  wellness-resource-service_data: